// Test generated by RoostGPT for test endtoendunit using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;

public class Product_getDescription_ca387c4bd2_Test {

    @Mock
    private Product product;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetDescription_Success() {
        String expectedDescription = "Test Product Description";
        Mockito.when(product.getDescription()).thenReturn(expectedDescription);
        
        String actualDescription = product.getDescription();
        Assertions.assertEquals(expectedDescription, actualDescription);
    }

    @Test
    public void testGetDescription_Null() {
        Mockito.when(product.getDescription()).thenReturn(null);
        
        String actualDescription = product.getDescription();
        Assertions.assertNull(actualDescription);
    }
}
