// Test generated by RoostGPT for test endtoendunit using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_setId_e7f341730a_Test {

    private Product product;

    @BeforeEach
    public void setUp() {
        product = new Product();
    }

    @Test
    public void testSetId_PositiveNumber() {
        Long id = 1L;
        product.setId(id);
        assertEquals(id, product.getId(), "The id should be set correctly");
    }

    @Test
    public void testSetId_NegativeNumber() {
        Long id = -1L;
        product.setId(id);
        assertEquals(id, product.getId(), "The id should be set correctly even if it's negative");
    }

    @Test
    public void testSetId_Zero() {
        Long id = 0L;
        product.setId(id);
        assertEquals(id, product.getId(), "The id should be set correctly even if it's zero");
    }

    @Test
    public void testSetId_Null() {
        product.setId(null);
        assertEquals(null, product.getId(), "The id should be set to null correctly");
    }
}
