// Test generated by RoostGPT for test endtoendunit using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

public class Product_setDescription_5d6a2c2267_Test {

    @InjectMocks
    private Product product;

    @BeforeEach
    public void init() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testSetDescription() {
        String expectedDescription = "This is a test product";
        product.setDescription(expectedDescription);
        Assertions.assertEquals(expectedDescription, product.getDescription());
    }

    @Test
    public void testSetDescriptionWithNull() {
        String expectedDescription = null;
        product.setDescription(expectedDescription);
        Assertions.assertNull(product.getDescription());
    }
}
