// Test generated by RoostGPT for test endtoendunit using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class Product_getId_eb19b6a6d6_Test {

    @InjectMocks
    private Product product;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetIdWithNullId() {
        assertNull(product.getId());
    }

    @Test
    public void testGetIdWithNonNullId() {
        Long expectedId = 1L;
        product.setId(expectedId);
        Long actualId = product.getId();
        assertEquals(expectedId, actualId);
    }
}
