// Test generated by RoostGPT for test endtoendunit using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_setPrice_fa182f5c65_Test {

    @Test
    public void testSetPricePositive() {
        Product product = new Product();
        double expectedPrice = 200.0;
        product.setPrice(expectedPrice);
        assertEquals(expectedPrice, product.getPrice(), "The price should be set correctly for positive values");
    }

    @Test
    public void testSetPriceNegative() {
        Product product = new Product();
        double expectedPrice = -200.0;
        product.setPrice(expectedPrice);
        assertEquals(expectedPrice, product.getPrice(), "The price should be set correctly for negative values");
    }

    @Test
    public void testSetPriceZero() {
        Product product = new Product();
        double expectedPrice = 0.0;
        product.setPrice(expectedPrice);
        assertEquals(expectedPrice, product.getPrice(), "The price should be set correctly for zero value");
    }
}
