// Test generated by RoostGPT for test endtoendunit using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_getPrice_d97185b3e6_Test {

    private Product product;

    @BeforeEach
    public void setUp() {
        product = Mockito.mock(Product.class);
    }

    @Test
    public void testGetPrice() {
        // TODO: Set the price of the product here
        double expectedPrice = 100.0;
        Mockito.when(product.getPrice()).thenReturn(expectedPrice);

        double actualPrice = product.getPrice();

        assertEquals(expectedPrice, actualPrice, "The expected price does not match the actual price");
    }

    @Test
    public void testGetPrice_Zero() {
        double expectedPrice = 0.0;
        Mockito.when(product.getPrice()).thenReturn(expectedPrice);

        double actualPrice = product.getPrice();

        assertEquals(expectedPrice, actualPrice, "The expected price does not match the actual price");
    }
}
