// Test generated by RoostGPT for test endtoendunit using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_getId_eb19b6a6d6_Test {

    @InjectMocks
    private Product product;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetId_Success() {
        Long expectedId = 123L;
        product.setId(expectedId);
        Long actualId = product.getId();
        assertEquals(expectedId, actualId, "The ID returned by getId() didn't match the expected value.");
    }

    @Test
    public void testGetId_Null() {
        product.setId(null);
        Long actualId = product.getId();
        assertEquals(null, actualId, "The ID returned by getId() should have been null but it wasn't.");
    }
}
