// Test generated by RoostGPT for test endtoendunit using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_getName_8400ac6fb7_Test {

    private Product product;

    @BeforeEach
    public void setUp() {
        product = new Product();
    }

    @Test
    public void testGetName_WhenNameIsSet() {
        // TODO: replace "TestProduct" with the actual product name you want to test
        String expectedProductName = "TestProduct";
        product.setName(expectedProductName);

        String actualProductName = product.getName();

        assertEquals(expectedProductName, actualProductName, "Product name should match the set name");
    }

    @Test
    public void testGetName_WhenNameIsNotSet() {
        String actualProductName = product.getName();

        assertEquals(null, actualProductName, "Product name should be null when it is not set");
    }
}
