// Test generated by RoostGPT for test endtoendunit using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_getPrice_d97185b3e6_Test {

    private Product product;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        product = new Product();
    }

    @Test
    public void testGetPrice_PositiveValue() {
        double expectedPrice = 100.0;
        product.setPrice(expectedPrice);
        double actualPrice = product.getPrice();
        assertEquals(expectedPrice, actualPrice, "Expected and actual price should match");
    }

    @Test
    public void testGetPrice_ZeroValue() {
        double expectedPrice = 0.0;
        product.setPrice(expectedPrice);
        double actualPrice = product.getPrice();
        assertEquals(expectedPrice, actualPrice, "Expected and actual price should match when price is zero");
    }

    @Test
    public void testGetPrice_NegativeValue() {
        double expectedPrice = -10.0;
        product.setPrice(expectedPrice);
        double actualPrice = product.getPrice();
        assertEquals(expectedPrice, actualPrice, "Expected and actual price should match when price is negative");
    }
}
