// Test generated by RoostGPT for test endtoendunit using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_setPrice_fa182f5c65_Test {
    private Product product;

    @BeforeEach
    public void setup() {
        product = new Product();
    }

    @Test
    public void testSetPrice_Positive() {
        product.setPrice(100.50);
        assertEquals(100.50, product.getPrice(), "Prices should match");
    }

    @Test
    public void testSetPrice_Zero() {
        product.setPrice(0);
        assertEquals(0, product.getPrice(), "Prices should match");
    }

    @Test
    public void testSetPrice_Negative() {
        product.setPrice(-100.50);
        assertEquals(-100.50, product.getPrice(), "Prices should match");
    }
}
