// Test generated by RoostGPT for test endtoendunit using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.mockito.Mockito;

public class Product_setName_f5bd015150_Test {

    private Product product;

    @BeforeEach
    public void setUp() {
        product = new Product();
    }

    @Test
    public void testSetName() {
        String expectedName = "TestProduct";
        product.setName(expectedName);
        Assertions.assertEquals(expectedName, product.getName());
    }

    @Test
    public void testSetNameWithNull() {
        String expectedName = null;
        product.setName(expectedName);
        Assertions.assertEquals(expectedName, product.getName());
    }
}
