// Test generated by RoostGPT for test endtoendunit using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_setId_04a8e16b7c_Test {

    private Product product;

    @BeforeEach
    public void setUp() {
        product = new Product();
    }

    @Test
    public void testSetId_Success() {
        Long expectedId = 123L;
        product.setId(expectedId);
        assertEquals(expectedId, product.getId(), "The expected ID does not match the actual ID");
    }

    @Test
    public void testSetId_Null() {
        product.setId(null);
        assertEquals(null, product.getId(), "The expected ID does not match the actual ID");
    }
}
