// Test generated by RoostGPT for test endtoendunit using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Product_getDescription_ca387c4bd2_Test {

    private Product product;

    @BeforeEach
    public void setup() {
        product = new Product();
    }

    @Test
    public void testGetDescription_withDescription() {
        String expectedDescription = "This is a test product.";
        product.setDescription(expectedDescription);
        assertEquals(expectedDescription, product.getDescription());
    }

    @Test
    public void testGetDescription_withoutDescription() {
        String expectedDescription = null; // TODO: Change this value to match your expected outcome
        assertEquals(expectedDescription, product.getDescription());
    }
}
