// Test generated by RoostGPT for test endtoendunit using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_setPrice_fa182f5c65_Test {

    private Product product;

    @BeforeEach
    public void setUp() {
        product = new Product();
    }

    @Test
    public void testSetPrice_positiveNumber() {
        double price = 100.0;
        product.setPrice(price);
        assertEquals(price, product.getPrice(), "Price should be set to the positive number");
    }

    @Test
    public void testSetPrice_zero() {
        double price = 0.0;
        product.setPrice(price);
        assertEquals(price, product.getPrice(), "Price should be set to zero");
    }

    @Test
    public void testSetPrice_negativeNumber() {
        double price = -100.0;
        product.setPrice(price);
        assertEquals(price, product.getPrice(), "Price should be set to the negative number");
    }
}
